kind = "web"
previewPath = "/"
title = "Special Message"
version = "1.0.0"
id = "artifacts/special-message"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 26024

[services.development]
run = "pnpm --filter @workspace/special-message run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/special-message", "run", "build" ]
serve = "static"
publicDir = "artifacts/special-message/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "26024"
BASE_PATH = "/"
